# Generated by Django 3.0.3 on 2020-02-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('hostname', 'account')},
        ),
    ]
