# Generated by Django 3.0.3 on 2020-02-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200223_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='type',
            field=models.CharField(choices=[('ping', 'ping'), ('black', 'blacklist')], default='ping', max_length=5),
        ),
    ]
