# Generated by Django 3.0.3 on 2020-03-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alert_contact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('phone', 'email')},
        ),
    ]
