# Generated by Django 3.0.3 on 2020-03-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200309_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.Account'),
            preserve_default=False,
        ),
    ]
