# Generated by Django 3.0.3 on 2020-04-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200309_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='contacts',
            field=models.ManyToManyField(related_name='alerts', to='core.Contact'),
        ),
    ]
