# Generated by Django 3.0.3 on 2020-04-06 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alert_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='options',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='contacts',
            field=models.ManyToManyField(to='core.Contact'),
        ),
    ]
