# Generated by Django 3.0.3 on 2020-04-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200406_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
